name: Update packages

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */12 * * *


env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    name: Update Packages
    strategy:
      fail-fast: false

        
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x packages.sh
        git clone https://github.com/ykxVK8yL5L/packages.git
        cd packages
        rm -rf *
        git rm --cache *
        $GITHUB_WORKSPACE/packages.sh

    - name: Upload
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        [ -e $GITHUB_WORKSPACE/.github ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/packages
        [ -e $GITHUB_WORKSPACE/.gitignore ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/packages
        [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/packages
        [ -e $GITHUB_WORKSPACE/packages.sh ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/packages
        cd $GITHUB_WORKSPACE/packages
        git add .
        git commit -m "update$(TZ='Asia/Shanghai' date +@%Y%m%d)"
        git push --quiet "https://${{ secrets.TOKEN }}@github.com/ykxVK8yL5L/packages.git"
 
